apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 1
  template: 
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: sampleproject
        image: meraki2010/sampleproject:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
 name: sample-service
spec:
 type: NodePort
 selector:
   app: demoapp
 ports:
   - port: 80
     nodePort: 30030

